### PR TITLE
fix: deserialization for PromptCase with interface inference

### LINKED ISSUE #305: Scripted client chooses the wrong interface in prompt filter
I'm working on adding a new integration test spread variant for special characters, to test the snapd fix which escapes special characters in prompts.

Snapd PR: https://github.com/canonical/snapd/pull/16854

This addresses https://github.com/canonical/desktop-security-center/issues/188

However, `prompting-client.scripted` is decoding the second prompt filter in the sequence as a `camera` prompt, instead of a `home` prompt:

```
Attempt to read the first file
+ snap run --shell prompting-client.scripted -c cat /home/test/integration-tests/tmp.52HHn4492c/'[アニメ][ゲーム動画].mkv'
+ FIRST_OUTPUT=a file with square brackets and unicode
+ echo Attempt to read the second file
Attempt to read the second file
+ snap run --shell prompting-client.scripted -c cat /home/test/integration-tests/tmp.52HHn4492c/'foo*?()[]{}\'
failed prompt sequence: expected next prompt to have interface=camera but got home

script: {
  "version": 1,
  "prompt-filter": {
    "snap": "prompting-client",
    "interface": "home",
    "constraints": {
      "path": "/home/test/integration-tests/tmp.52HHn4492c/.*"
    }
  },
  "prompts": [
    {
      "prompt-filter": {
        "constraints": {
          "path": "/home/test/integration-tests/tmp.52HHn4492c/\\\\\\[アニメ\\\\\\]\\\\\\[ゲーム動画\\\\\\].mkv",
          "requested-permissions": [ "read" ]
        }
      },
      "reply": {
        "action": "allow",
        "lifespan": "single",
        "constraints": {
          "path-pattern": "/home/test/integration-tests/tmp.52HHn4492c/\\[アニメ\\]\\[ゲーム動画\\].mkv",
          "permissions": [ "read" ]
        }
      }
    },
    {
      "prompt-filter": {
        "constraints": {
          "path": "/home/test/integration-tests/tmp.52HHn4492c/foo\\\\*\\\\?()\\\\[\\\\]\\\\{\\\\}\\\\\\\\",
          "requested-permissions": [ "read" ]
        }
      },
      "reply": {
        "action": "allow",
        "lifespan": "single",
        "constraints": {
          "path-pattern": "/home/test/integration-tests/tmp.52HHn4492c/foo\\*\\?()\\[\\]\\{\\}\\\\",
          "permissions": [ "read" ]
        }
      }
    }
  ]
}

failed
cat: '/home/test/integration-tests/tmp.52HHn4492c/foo*?()[]{}\': Permission denied
```

Link to failure in CI: https://github.com/canonical/snapd/actions/runs/24409321016/job/71305198912?pr=16854#step:25:204

This can be reproduced locally by doing the following:

1. Ensure `snapcraft` is installed with lxd initialized
2. `snap install image-garden`
3. `sudo snap set image-garden spread-variant=plus`
4. `sudo snap alias image-garden.spread spread`
5. `git clone https://github.com/olivercalder/snapd -b prompting-escape-prompt-path` and `cd` into the project directory
6. `./run-spread -v garden:ubuntu-24.04-64:tests/main/apparmor-prompting-integration-tests:special_characters`
7. (If you'd like to re-run after tweaking code in `tests`, you can use `NO_REBUILD=1` to prevent the snapd snap from being rebuilt, which takes a while)

### PR DESCRIPTION
**Pull request by gabelluardo**
This fixes a deserialization issue for the scripted client's `TypedPromptCase` enum. 

The `untagged` Serde macro previously defaulted to the first loose match based on definition order. With the new `deserialize_prompt_case function`, we can now identify the correct interface based on JSON fields. To avoid ambiguity, we should mandate an `interface` field in all prompt-filter JSON objects.

Fixes #305

---

UDENG-9866

### CODE REVIEW

File: prompting-client/src/prompt_sequence.rs [hunk 1]
```diff
@@ -108,11 +108,64 @@ fn apply_vars(mut content: String, vars: &[(&str, &str)]) -> String {
...
+    match interface {
+        Some(name) if name == T::NAME => {}
+
+        // Deserialized with the wrong interface type.
+        Some(name) => {
+            return Err(de::Error::invalid_value(
+                de::Unexpected::Str(name),
+                &"matching interface",
+            ));
+        }
```
Comment (olivercalder) [inline prompting-client/src/prompt_sequence.rs:143]: Nitpick/suggestion, maybe what you have is more consistent

```suggestion
        // Deserialized with the wrong interface type.
        Some(name) if name != T::NAME => {
            return Err(de::Error::invalid_value(
                de::Unexpected::Str(name),
                &"matching interface",
            ));
        }
```

File: prompting-client/src/prompt_sequence.rs [hunk 2]
```diff
@@ -108,11 +108,64 @@ fn apply_vars(mut content: String, vars: &[(&str, &str)]) -> String {
...
 #[derive(Debug, Serialize, Deserialize)]
 #[serde(untagged)]
 enum TypedPromptCase {
-    Home(PromptCase<HomeInterface>),
+    #[serde(deserialize_with = "deserialize_prompt_case")]
     Camera(PromptCase<CameraInterface>),
+    #[serde(deserialize_with = "deserialize_prompt_case")]
+    Home(PromptCase<HomeInterface>),
+    #[serde(deserialize_with = "deserialize_prompt_case")]
     Microphone(PromptCase<MicrophoneInterface>),
```
Comment (olivercalder) [inline prompting-client/src/prompt_sequence.rs:169]: So then for each of these, does it try to deserialize to a given variant, and if there's an error, try the next one?

**Review by olivercalder — APPROVED** [review]
Thanks for fixing this!

I'm really confused why basically every prompt sequence has been correctly deserialized as a home prompt, but then it consistently deserialized this one as a camera prompt: https://github.com/canonical/snapd/pull/16931/changes/ec6bd83f7e7134509b9e5641d629ee1ec2ec393c

Very weird. Anyway, this should fix it, so thank you!

File: prompting-client/src/prompt_sequence.rs (hunk 1 above)
Comment (gabelluardo) [reply prompting-client/src/prompt_sequence.rs:143]: The fact is the compiler expects one bare `Some(_) => {}` so my intention is to make more explicit the happy path like for https://github.com/canonical/prompting-client/blob/e8f0f3fdec209eaba85d9c0c1245b6c18fd67b96/prompting-client/src/prompt_sequence.rs#L145-L146

File: prompting-client/src/prompt_sequence.rs (hunk 2 above)
Comment (gabelluardo) [reply prompting-client/src/prompt_sequence.rs:169]: Exactly, with only the `untagged` macro it works the same, but because the unknown fields are ignored serde takes the first variant with no errors. When we had only the `home` interface this worked good enough but as we add more interfaces it creates ambiguity and a json like


```json
{
  "prompt-filter": {
    "constraints": {
        "path": "...",
        "requested-permissions": [ "read" ]
    }
  },
  "reply": {}
}
```

is misinterpreted like a `Camera(PromptCase<CameraInterface>)` ignoring the `path` field but matching all the required fields for that type.

**Review by d-loose — APPROVED** [review]
Thanks, all this makes a lot more sense now!

File: prompting-client/src/prompt_sequence.rs (hunk 1 above)
Comment (olivercalder) [reply prompting-client/src/prompt_sequence.rs:143]: Ah yes, exhaustive matching, so yeah what you have is good
