### PR TITLE
fix: microphone interface deserialization with correct `audio-record` field name

### LINKED ISSUE #307: `prompting-client.scripted` doesn't expect `audio-record` interface
I believe there's an issue with deserializing scripted client scripts. Namely, the expected interfaces are `home`, `camera`, and `microphone`, rather than `audio-record`.

Here's a log where I'm trying to create a script which filters on `audio-record` prompts:

```
creating client
script path: /home/test/integration-tests/tmp.kjBUacb7DW/script.json
Error: Json(Error("unknown variant `audio-record`, expected one of `camera`, `home`, `microphone`", line: 5, column: 31))
failed
```

I think the issue has to do with this, where it seems the enum tags are deserialized as kebab case, while actually the `SnapInterface::Name` should be used:

https://github.com/canonical/prompting-client/blob/e8ffdbee2b43ce9b8586d9df24653f87f1932c34/prompting-client/src/prompt_sequence.rs#L186-L195

The `Microphone` tag thus gets unmarshalled as `"microphone"`, rather than being properly unmarshalled as `"audio-record"`.

Probably, for consistency/easy of understanding/debugging, it would be better if all the microphone-related types were renamed to audio-record instead. I think the only mention of "microphone" should be in the text displayed in the prompts to the users.

### PR DESCRIPTION
**Pull request by gabelluardo**
Fixes #307

Refactored serde deserialization functions in order to rely directly on `Interface::NAME` instead of enum fields name or redundant `rename` macros.

### CODE REVIEW

**Review by d-loose — APPROVED** [review]

File: prompting-client/src/prompt_sequence.rs [hunk 1]
```diff
@@ -108,92 +108,138 @@ fn apply_vars(mut content: String, vars: &[(&str, &str)]) -> String {
...
+            }
+        }
+
+        Ok(case)
+    }
 }
 
-#[derive(Debug, Serialize, Deserialize)]
-#[serde(tag = "interface", rename_all = "kebab-case")]
+#[derive(Debug, Serialize)]
```
Comment (olivercalder) [inline prompting-client/src/prompt_sequence.rs]: These still derive `Serialize`, does that mean that they will still default to `"microphone"`, for example? Also, is there a reason these need to be serializable at all? I would think they should just need to be deserializable, except maybe in tests if you want to test round-trip {,de}serialization.

**Review by olivercalder — APPROVED** [review]
Looks great, thanks for the fix! Much clearer I think to explicitly use `::Name` everywhere.

File: prompting-client/src/prompt_sequence.rs (hunk 1 above)
Comment (gabelluardo) [reply prompting-client/src/prompt_sequence.rs]: Agree, we actually don't need to serialize them. For tests we can easly add and remove as we do for `dbg!()`, but I think we can safely drop this trait for prod
